site_name: Inmaculada Chorus
nav:
  - Home: index.md
  - Miercoles de Ceniza: miercoles_de_ceniza.md
  - Exequias: exequias.md
  - Repertorio: repertorio.md
  - Ramos: ramos.md
  - Viernes Santo: viernes_santo.md
  - Boda: boda.md
  - Maria: maria.md
  - Teresita: teresita.md
  - Hora Santa: hora_santa.md
  - Seminario: seminario.md
  - Fin de Año: fin_anio.md
  - Jueves Santo: jueves_santo.md
  - Sabado Santo: sabado_santo.md
  - Pentecostés: pentecostes.md
  - Quince Años: quince_anios.md
  - Misa de Miercoles: miercoles.md
  - San Francisco: san_francisco.md
  - Fieles Difuntos: fieles_difuntos.md
  - Entrada:
      - Dios es amor: entrada/dios_es_amor.md
      - el espiritu del señor: entrada/el_espiritu_del_senior.md
      - ha vencido el cordero: entrada/ha_vencido_el_cordero.md
      - que alegría cuando me dijeron: entrada/que_alegria_cuando_me_dijeron.md
      - salmo 115: entrada/salmo_115.md
      - vamos al altar: entrada/vamos_al_altar.md
      - yo celebraré: entrada/yo_celebrare.md
      - vamos cantando al señor: entrada/vamos_cantando_al_senior.md
      - yo celebraré: entrada/yo_celebrare.md
      - ven señor no tardes: entrada/ven_senior_no_tardes.md
      - A tu altar: entrada/a_tu_altar.md
      - Canta al Señor un canto nuevo: entrada/canta_al_senor_un_canto_nuevo.md
      - El cielo canta alegria: entrada/el_cielo_canta_alegria.md
      - El Señor es compasivo: entrada/el_senior_es_compasivo.md
      - El Señor resucitó: entrada/el_senior_resucito.md
      - Salmo 62: entrada/salmo_62.md
      - Venimos hoy a tu altar: entrada/venimos_hoy_a_tu_altar.md
      - Jerusalen: entrada/jerusalen.md
      - Portones: entrada/portones.md
      - Alabemos a Maria: entrada/alabemos_a_maria.md

  - Señor:
      - señor (1): senior_ten_piedad/senior_1.md
      - señor (2): senior_ten_piedad/senior_2.md
      - señor (3): senior_ten_piedad/senior_3.md
      - señor (4): senior_ten_piedad/senior_4.md
      - señor (5): senior_ten_piedad/senior_5.md
      - señor (6): senior_ten_piedad/senior_6.md
      - señor (7): senior_ten_piedad/senior_7.md
  - Gloria:
      - gloria (1): gloria/gloria_1.md
      - gloria (2): gloria/gloria_2.md
      - gloria (3): gloria/gloria_3.md
      - gloria (4): gloria/gloria_4.md
      - gloria (5): gloria/gloria_5.md
      - Gloria (6): gloria/gloria_6.md
      - gloria nortino: gloria/gloria_nortino.md
      - gloria in excelsis deo: gloria/Gloria_in_excelsis_deo.md
  - Aleluya:
      - Aleluya 1: aleluya/aleluya_1.md
      - Aleluya 2: aleluya/aleluya_2.md
      - Aleluya 3: aleluya/aleluya_3.md
      - himno de paz: aleluya/himno_de_paz.md
      - aleluya D: aleluya/aleluya_d.md
      - aleluya G: aleluya/aleluya_g.md
  - Honor y Gloria:
      - Honor y Gloria (1): honor_y_gloria/honor_y_gloria_1.md
      - Honor y Gloria (2): honor_y_gloria/honor_y_gloria_2.md
      - Honor y Gloria (3): honor_y_gloria/honor_y_gloria_3.md
  - Ofertorio:
      - con el vino y con el pan: ofertorio/con_el_vino_y_con_el_pan.md
      - con estas ofrendas: ofertorio/con_estas_ofrendas.md
      - esto que te doy: ofertorio/esto_que_te_doy.md
      - padre nuestro recibid: ofertorio/padre_nuestro_recibid.md
      - te presentamos el vino y el pan: ofertorio/te_presentamos_el_vino_y_el_pan.md
      - toma nuestros corazones: ofertorio/toma_nuestros_corazones.md
      - En este mundo: ofertorio/en_este_mundo.md
      - Entre tus manos: ofertorio/entre_tus_manos.md
      - Hemos entregado: ofertorio/hemos_entregado.md
      - Sobre tu altar: ofertorio/sobre_tu_altar.md
      - Te ofrecemos padre nuestro: ofertorio/te_ofrecemos_padre_nuestro.md
      - Vino y pan: ofertorio/vino_y_pan.md
      - Llevemos al Señor: ofertorio/llevemos_al_sr_el_vino_y_el_pan.md
  - Santo:
      - santo (1): santo/santo_1.md
      - santo (2): santo/santo_2.md
      - santo (3): santo/santo_3.md
      - santo (4): santo/santo_4.md
      - santo (5): santo/santo_5.md
      - santo Tradicional: santo/santo_tradicional.md
  - Consagracion:
      - jesus hijo de david: consagracion/jesus_hijo_de_david.md
      - me consagro a ti: consagracion/me_consagro_a_ti.md
      - vive jesus el señor: consagracion/vive_jesus_el_senior.md
      - Entrare: consagracion/entrare.md
      - Venimos a adorar: consagracion/venimos_a_adorar.md
      - Dame tu mano: consagracion/dame_tu_mano.md
      - Rendid honor al señor: consagracion/rendid_honor_al_senor.md
      - solo Dios: consagracion/solo_dios.md
      - te entrego: consagracion/te_entrego.md
      - Rendid honor al Señor: consagracion/rendid_honor_al_senor.md
  - Cordero:
      - cordero (1): cordero/cordero_1.md
      - cordero (2): cordero/cordero_2.md
      - cordero (3): cordero/cordero_3.md
      - cordero (4): cordero/cordero_4.md
      - cordero (5): cordero/cordero_5.md
      - cordero (6): cordero/corder_6.md
      - cordero (7): cordero/cordero_7.md
  - Comunión:
      - Hago Nuevas todas las cosas: comunion/hago_nuevas_todas_las_cosas.md
      - Hazme un instrumento de tu paz: comunion/hazme_un_instrumento_de_tu_paz.md
      - Permanecer en ti: comunion/permanecer_en_ti.md
      - Vida en abundancia: comunion/vida_en_abundancia.md
      - el señor es mi pastor: comunion/el_senior_es_mi_pastor.md
      - en la eucaristía: comunion/en_la_eucaristia.md
      - estoy a la puerta y llamo: comunion/estoy_a_la_puerta_y_llamo.md
      - incomparable: comunion/incomparable.md
      - señor a quien iremos: comunion/senior_a_quien_iremos.md
      - un mandamiento nuevo: comunion/un_mandamiento_nuevo.md
      - ven: comunion/ven.md
      - verbum panis: comunion/verbum_panis.md
      - ya no eres pan y vino: comunion/ya_no_eres_pan_y_vino.md
      - levantate: comunion/levantate.md
      - milagro de amor: comunion/milagro_de_amor.md
      - Alma misionera: comunion/ALMA_MISIONERA.md
      - Aqui estoy señor: comunion/aqui_estoy_senior.md
      - El amor de mi Dios: comunion/el_amor_de_mi_dios.md
      - Eterno viajero: comunion/eterno_viajero.md
      - Hambre de Dios: comunion/hambre_de_Dios.md
      - Mirad jesus resucita: comunion/mirad_jesus_resucita_hoy.md
      - Renace la esperanza: comunion/renace_la_esperanza.md
      - Tanto amó Dios al mundo: comunion/tanto_amo_dios_al_mundo.md
      - Tu señor: comunion/tu_senior.md
      - presentacion del señor: comunion/presentacion_del_senior.md
      - Una estrella: comunion/una_estrella.md
      - Ven y sigueme: comunion/ven_y_sigueme.md
  - Salida:
      - A ti madre de esperanza: salida/a_ti_madre_de_esperanza.md
      - En torno a María: salida/en_torno_a_maria.md
      - Junto a tí María: salida/junto_a_ti_maria.md
      - Las aves van: salida/las_aves_van.md
      - Madre del divino pan: salida/madre_del_divino_pan.md
      - Madre oferente: salida/madre_oferente.md
      - María mírame: salida/maria_mirame.md
      - Mi estandarte: salida/mi_estandarte.md
      - Piensa en María: salida/piensa_en_maria.md
      - Santa María del Camino: salida/santa_maria_del_camino.md
      - Una entre todas: salida/una_entre_todas.md
      - Dijiste si: salida/dijiste_si.md
      - Madre de nuestra alegría: salida/madre_de_nuestra_alegria.md
      - Madre del silencio: salida/madre_del_silencio.md
      - Perpetuo Socorro: salida/perpetuo_socorro.md
      - Quiero Madre: salida/quiero_madre.md
      - Te doy gracias Jesus: salida/te_doy_gracias_jesus.md
      - Tomaste mis manos: salida/tomaste_mis_manos.md
      - Niña que nacio: salida/ninia_que_nacio.md
  - Penteocostés:
      - ven espíritu de Dios: pentecostes/ven_espiritu_de_dios.md
      - el espíritu de Dios: pentecostes/el_espiritu_de_dios.md
      - algo va descendiendo: pentecostes/algo_va_descendiendo.md
      - Entra: espiritu_santo/entra.md
      - Haz llover: espiritu_santo/haz_llover.md
      - Ven espiritu: espiritu_santo/ven_espiritu.md
      - Ven solo ven: espiritu_santo/ven_solo_ven.md
  - Trinidad:
      - Dios mio, trinidad a quien adoro: trinidad/trinidad_a_quien_adoro.md
      - Dios trino: trinidad/dios_trino.md
      - Gozo de la trinidad: trinidad/gozo_de_la_trinidad.md
      - Gloria grinitario: trinidad/gloria_trinitario.md
  - Pascua:
      - Alegre la mañana: pascua/alegre_la_maniana.md
  - Alabanzas:
      - Alabare: alabanzas/alabare.md
      - Baja el rio: alabanzas/baja_el_rio.md
      - El leon de la tribu: alabanzas/el_leon_de_la_tribu.md
      - El poderoso de israel: alabanzas/el_poderoso_de_israel.md
      - Este dia nos vamos a gozar: alabanzas/este_dia_nos_vamos_a_gozar.md
      - Granito de mostaza: alabanzas/mostaza.md
      - Remolineando: alabanzas/remolineando.md
  - Boda:
      - Entrada: boda/salmo_115.md
      - Entrada: boda/desde_que_voy.md
      - Aleluya: boda/aleluya.md
      - Ofertorio: boda/quiero_estar_senior.md
      - Ofertorio: boda/ofertorio.md
      - Santo: boda/santo.md
      - Cordero: boda/corder.md
      - Comunion: boda/comunion.md
      - Salida: boda/de_aqui_hasta_el_final.md
      - Salida: boda/forma_de_amar.md
  - Miercoles de Ceniza:
      - Caminare: ceniza/caminare.md
      - Señor: ceniza/senior.md
      - Con estas cenizas: ceniza/con_estas_cenizas.md
      - Cordero: ceniza/cordero.md
      - Perdona a tu pueblo: ceniza/perdona_a_tu_pueblo.md
      - Pescador de hombres: ceniza/pescador_de_hombres.md
      - Santo: ceniza/santo.md
  - Exequias:
      - Caminare: exequias/caminare.md
      - Señor: exequias/senior.md
      - Aleluya: exequias/aleluya.md
      - Ofertorio: exequias/ofertorio.md
      - Santo: exequias/santo.md
      - Cordero: exequias/cordero.md
      - Comunion: exequias/yo_soy_el_pan_de_vida.md
      - Salida: exequias/salida.md
  - Semana Santa:
      - Amando hasta el extremo: jueves_santo/amando_hasta_el_extremo.md
      - Pueblo de Reyes: jueves_santo/pueblo_de_reyes.md
      - Ubi Caritas: jueves_santo/ubi_caritas.md
      - Un Mandamiento nuevo: jueves_santo/un_mandamiento_nuevo.md
      - Aleluya: sabado_santo/aleluya.md
      - Bautizame: sabado_santo/bautizame_senior.md
      - Bendicion del agua: sabado_santo/bendicion_del_agua.md
      - Corder: sabado_santo/cordero_3.md
      - El leon de la tribu de juda: sabado_santo/el_leon_de_la_tribu.md
      - Gloria: sabado_santo/gloria.md
      - Hemos entregado: sabado_santo/hemos_entregado.md
      - Llevemos al Señor el vino y el pan: sabado_santo/llevemos_al_sr_el_vino_y_el_pan.md
      - Quiero estar Señor: sabado_santo/quiero_estar_senior.md
      - Renace la esperanza: sabado_santo/renace_la_esperanza.md
      - Resucitó: sabado_santo/resucito.md
      - Santo: sabado_santo/santo_3.md
  - Ramos:
      - Tu reninaras: ramos/tu_reinaras.md
      - Tu reino es vida: ramos/tu_reino_es_vida.md
      - Viva cristo rey: ramos/viva_cristo_rey.md
  - Teresita:
      - A Teresita: teresita/a_teresita.md
      - Aleluya: teresita/aleluya.md
      - Cordero sevillano: teresita/cordero_sevillano.md
      - De aquí hasta el final: teresita/de_aqui_hasta_el_final.md
      - El abandono: teresita/el_abandono.md
      - En la eucaristía: teresita/en_la_eucaristia.md
      - Estoy a la puerta y llamo: teresita/estoy_a_la_puerta_y_llamo.md
      - Florecilla del carmelo: teresita/florecilla_de_carmelo.md
      - Gloria: teresita/gloria_1.md
      - Incomparable: teresita/incomparable.md
      - Santo: teresita/santo_1.md
      - Señor ten piedad: teresita/senior.md
      - Toma nuestros corazones: teresita/toma_nuestros_corazones.md
  - Vocacionales:
      - Aleluya: vocacionales/aleluya.md
      - Cordero: vocacionales/cordero.md
      - Dijiste si: vocacionales/dijiste_si.md
      - Gloria: vocacionales/gloria.md
      - Jerusalen: vocacionales/jerusalen.md
      - Profeta: vocacionales/profeta.md
      - Santo: vocacionales/santo.md
      - Señor: vocacionales/senior.md
      - Sobre tu altar: vocacionales/sobre_tu_altar.md
  - Villancicos:
      - Campana sobre campana: villancicos/Campana_sobre_campana.md
      - El niño del tambor: villancicos/El_ninio_del_tambor.md
      - Peces en el rio: villancicos/Peces_en_el_rio.md
      - Adestes Fideles: navidad/adestes_fideles.md

#   - Historial:
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: light
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
